# Generated by Django 5.2.7 on 2025-11-19 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id_location', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id_paymentmethod', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id_promotion', models.AutoField(primary_key=True, serialize=False)),
                ('promocode', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id_season', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingTypes',
            fields=[
                ('id_shippingtype', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id_size', models.AutoField(primary_key=True, serialize=False)),
                ('size_label', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=16)),
                ('sub_status', models.BooleanField(default=False)),
                ('freq_purchase', models.CharField(max_length=32)),
                ('prev_purchases', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.locations')),
                ('id_paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.paymentmethods')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.categories')),
                ('id_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_datos.colors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('id_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_datos.seasons')),
                ('id_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_datos.sizes')),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField(blank=True, default=None, null=True)),
                ('review_rate', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True)),
                ('dsct_applied', models.BooleanField(default=False)),
                ('promo_used', models.BooleanField(default=False)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.customers')),
                ('id_paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.paymentmethods')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.products')),
                ('id_promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_datos.promotions')),
                ('id_shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_datos.shippingtypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
